sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEgoRKAWTTF77dCnUVw
    access-key-secret: mpuzpVeQuMErqWlJtGgQKyFO0xzM0t
    bucket-name: lhwaimai
  redis:
    host: localhost
    port: 6379
    password: root
    database: 10
  wechat:
    appid: wx4cb76cbc95da958e
    secret: b3a9c4a2e4909ee20f99bf542dc07e3e
#    微信支付
    mchid:
    mch-serial-no:
    private-key-file-path:
    api-v3-key:
    we-chat-pay-cert-file-path:
    notify-url:
    refund-notify-url:

